### ISSUE TITLE
Truncate ASCII values when significantDigits is specified

### ISSUE THREAD

**Issue by sensiasoft** [opensensorhub/osh-core#1]
<a href="https://github.com/mikebotts"><img src="https://avatars.githubusercontent.com/u/7469574?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [mikebotts](https://github.com/mikebotts)**
_Friday Jan 09, 2015 at 00:25 GMT_
_Originally opened as https://github.com/sensiasoft/sensorhub-core/issues/1_

---

When SWE Common output components have the significantDigits property specified, truncate the output values according to the significantDigits value (e.g. 45.3049 versus 45.3049038746526).

**Comment by alexrobin** [comment]
The plan is to do that with the new SWE data stream writer architecture that is also much faster

**Comment by alexrobin** [comment]
Implemented in 12320c3
