### ISSUE TITLE
server 404 when using demo client

### ISSUE THREAD

**Issue by GavinPalmer1984** [opensensorhub/osh-core#105]
osh-core v1.3.1

On Windows 10, double click the .bat file and go to (do refreshes as well):
http://localhost:8181/osm_client_websockets.html

![image](https://user-images.githubusercontent.com/5564129/33519429-e05b9eb2-d76b-11e7-8945-fdeb596609cd.png)

![image](https://user-images.githubusercontent.com/5564129/33519432-f0c59564-d76b-11e7-8ef3-e5bbf3369539.png)

**Comment by alexrobin** [comment]
This was caused by a bug in Jetty 9.4.7 that has now been fixed.
Release 1.3.3 will ship with Jetty 9.4.19.
