### ISSUE TITLE
SOS and IMultiSourceStorage

### ISSUE THREAD

**Issue by nicolas-f** [opensensorhub/osh-core#114]
If I understand the code, actually we must define one storage object per sensor in the Sensor Observation Service "Offerings" tab.

Do you think there is a lot of work to support multi source in the SOS service ?

**Comment by alexrobin** [comment]
Multisource is already supported in SOS.

Per the SOS service spec, one offering corresponds to one sensor, but it is possible to create a sensor driver that collects data from many similar sensors (e.g. environmental station networks, vehicle fleet, etc.). This type of sensor driver must implement IMultiSourceDataProducer, its data must be stored in a IMultiSourceStorage, and then it can be exposed as a single offering via SOS (features of interest - FOI - can then be used to select data from an individual sensor within the group).
