### ISSUE TITLE
V2.0 JarModuleProvider not providing manifest information

### ISSUE THREAD

**Issue by nickgaray** [opensensorhub/osh-core#169]
When adding a sensor module to a version 2 based OSH Node, the module list is populated with blank data unless the module descriptor has implemented the IModuleProvider interface.

Implementing the interface is a workaround.

**Comment by alexrobin** [comment]
Fixed in 1fd9b6e7.
Fields are not populated when running from IDE without building the module JAR but this is expected behavior
