### ISSUE TITLE
Admin UI Controls Subpanel Duplicates Controls and Reflects an Issue when Sending Command

### ISSUE THREAD

**Issue by nickgaray** [opensensorhub/osh-core#170]
The following are two distinct drivers showing duplication of controls, but also when commanding a sensor an error shows up.

![image](https://user-images.githubusercontent.com/37518594/116579610-29a4ca80-a8d8-11eb-8249-3fb7b520f39c.png)

![image](https://user-images.githubusercontent.com/37518594/116579632-30334200-a8d8-11eb-8624-93b991aef071.png)

**Comment by alexrobin** [comment]
Fixed in 6567849
