### ISSUE TITLE
Memory leak in SOS websocket impl

### ISSUE THREAD

**Issue by alexrobin** [opensensorhub/osh-core#172]
A memory leak becomes quickly visible when issuing many websocket requests. It impacts v1.4 and maybe v2.0

**Comment by alexrobin** [comment]
It seems the issue is caused by a reference to the websocket session that is not nullified on close

**Comment by mikebotts** [comment]
Alex. Does this affect how we should develop drivers or does it seem to be confined to core?

**Comment by alexrobin** [comment]
No impact on drivers. It's confined to core (SOS impl). Mathieu is working on a fix.

**Comment by mdhsl** [comment]
The memory leak appears when using the WebSocket service only. After investigation, we see that the listener of Jetty maintains a reference to the SOSWebSocketOut object which prevents it from being GC.

Next: https://stackoverflow.com/questions/55829525/potential-memory-leak-of-websocket-sessions-in-jetty-9-4-15

and updating Jetty to version 9.4.42.v20210604, the memory leak has gone.

The solution is simply to update Jetty

![image](https://user-images.githubusercontent.com/6577027/122439031-90bb3300-cf9b-11eb-8bf9-7f6bb777c93b.png)

**Comment by mikebotts** [comment]
Super. Good job. How might have this issue manifested itself in the server and in the COP?
