### ISSUE TITLE
ProcedureDriverTransactionHandler does not properly handle FoiEvent in v2

### ISSUE THREAD

**Issue by csdillard** [opensensorhub/osh-core#180]
`FoiEvent` extends `ProcedureEvent`, so the "else if" clause in [`ProcedureDriverTransactionHandler.handleEvent(...)`](https://github.com/opensensorhub/osh-core/blob/ee735e3a245952845d5abcf90b7bec90e35b9528/sensorhub-core/src/main/java/org/sensorhub/impl/procedure/ProcedureDriverTransactionHandler.java#L422) never gets called.

This prevents FOIs from being registered from `FoiEvent`s.

**Comment by codemanyak** [comment]
So the FoiEvent check should simply be done prior to the ProcedureEvent check (change if and else if).

**Comment by alexrobin** [comment]
Closed in branch v2 with f219159
