### ISSUE TITLE
SWE API historical playback with FOIs is out of order

### ISSUE THREAD

**Issue by csdillard** [opensensorhub/osh-core#196]
When you replay historical observations from a data stream with multiple FOIs, only one FOI's observations are sent correctly and all of the other FOI's observations are dumped simultaneously at the end.

Here is the URL path I'm using in testing. It requests a time period of three seconds.

`/sensorhub/api/datastreams/6ji9ix6v/observations?format=application/json&phenomenonTime=2022-02-01T15:55:35Z/2022-02-01T15:55:38Z&replaySpeed=1`

For the first three seconds, you get observations from only one FOI, replayed at the correct speed. Then the remaining observations for all other FOIs all get dumped at the end.

**Comment by alexrobin** [comment]
I cannot reproduce the issue using the latest from branch v2.
Can you test it with the latest and let me know if you're still experiencing the issue?
Thanks
