### ISSUE TITLE
sensorhub-webui-core

### ISSUE THREAD

**Issue by bogdanvaduva** [opensensorhub/osh-core#21]
Hi 
I've build OpenSensorHub from git, but when I tried to run it, I had an error saying "PropertyId enabled must be in the container". 
After spending some time trying to figure out why, I saw that the problem was coming from UIConstants.PROP_ENABLED which has been set up to "enabled". When I looked in ModuleConfig I saw that there was not property enabled, but autoStart. I changed the name in UIConstants from enabled to autoStart and it worked.
Hope it helps someone.

Regards.

**Comment by sensiasoft** [comment]
Hi Bogdan,

Yes I'm aware of this issue due to a small refactoring in the core.
I haven't committed the change yet because I'm working on other enhancements to the UI.

I'm glad you figured out the solution yourself.
Thanks for your feedback.
