### ISSUE TITLE
[database question V2] Editing data from outside OSH

### ISSUE THREAD

**Issue by gsedej** [opensensorhub/osh-core#217]
Hello!

I am interested in better data management of all saved data form OSH.

The new version of OSH, V2 is using H2 database (by adding `SystemDriverDatabase` and it's modue `MVObsSystemDatabase`.
I was able to use this database to save and load data from OSH, but I was not able to open database file (from disk) using H2 Web Console application. By inspecting V2 codebase for H2 (ex. `sensorhub-datastore-h2/src/main/java/org/sensorhub/impl/datastore/h2/MVFeatureDatabase.java`) I realized that its "only" using `MVstore` component of database.
Community of H2 said that MVstore files can't be edited in H2 Console, since it's not full database: https://stackoverflow.com/questions/72432698/h2-db-opening-example-file-in-web-console

Is there any way other way to "manage" database produced by OSH. Is it possible to use SQL on OSH database (online or offline)?
How could one for example delete all duplicated data?

P.S.: I didn't find better place for asking question.

**Comment by alexrobin** [comment]
Hi,

Thanks for your question.

Unfortunately there is currently no other persistence option than the embedded MVStore as we are still actively working on refining the data models. So there is currently no way to manage the content of the DB other than through OSH Java and Web APIs (or by developing custom code).

However, OSH datastore API is designed to integrate with any database backend (object DB / SQL / noSQL / cloud native DBs, etc.). Once the datastore data model is stable, our plan is to start implementing connectors to other well known databases.
