### ISSUE TITLE
Help needed to integrate DJI drones with OSH

### ISSUE THREAD

**Issue by charles-zablit** [opensensorhub/osh-core#230]
Hello,

We are a team of 3 students working on integrating a DJI drone with OpenSensorHub.

Our first idea was to live stream the drone's video to an RTMP server using the drone's built-in capabilities and then forward the stream to OSH.

However, this does not allow us to send telemetry data, which we are also interested in.

Would it be possible for you to provide an example of a DJI drone that has been integrated with OSH? Or any other information that could help us to achieve this.

Thank you in advance,
Charles Zablit

**Comment by alexrobin** [comment]
The closest thing is an example integration with a MavLink system in osh-addons:
https://github.com/opensensorhub/osh-addons/tree/master/sensors/robotics/sensorhub-driver-mavlink

Regarding video, you can indeed use the RTSP/RTP driver to get data from it, either directly, or through a ground proxy. We have done it successfully with 3DR drones in the past.
