### ISSUE TITLE
Subsystems not shown when more than 1 Sensor System configured

### ISSUE THREAD

**Issue by nickgaray** [opensensorhub/osh-core#238]
Subsystems (members) are not retrieved properly when there are more than 1 Sensor System configured on a node.

See screenshots below:
![image](https://github.com/opensensorhub/osh-core/assets/37518594/3512707c-b3c6-465a-8f6b-d57c142fe13c)
![image](https://github.com/opensensorhub/osh-core/assets/37518594/b11245c8-3bb1-42d2-9587-01b94c7ab62e)
![image](https://github.com/opensensorhub/osh-core/assets/37518594/738a4f6d-1327-4265-89b5-fce423b35931)
![image](https://github.com/opensensorhub/osh-core/assets/37518594/21c549ea-6b2f-432f-a63a-8931e87ba000)

**Comment by alexrobin** [comment]
Is this happening with or without configuring a database?

**Comment by alexrobin** [comment]
It should be fixed in v2 branch. Can you test again and reopen the issue if not? Thanks

**Comment by nickgaray** [comment]
This indeed has been fixed!
