### ISSUE TITLE
Remove frame dropping for MP4-H264 video

### ISSUE THREAD

**Issue by mikebotts** [opensensorhub/osh-core#28]
A frame dropping capability was added to video stream supporting MJPEG in order to prevent the video stream from getting further and further behind if the network could not keep up. This works OK for MJPEG because each frame is complete. However, in MP4-H264 video streams there are keyframes that are required by subsequent frames in order to render an image.

We found the frame dropping in MP4 streams to be overly aggressive and ineffective during the DryRun at Lorton, VA. Remove frame dropping in MP4.

**Comment by sensiasoft** [comment]
It is now possible to set a maximum queue size in the SOS-T client config to avoid dropping records too quickly. If one wants to make sure records (such as H264 frames) are never dropped, the queue size can be set very large.
