### ISSUE TITLE
Add notification support in SOS

### ISSUE THREAD

**Issue by sensiasoft** [opensensorhub/osh-core#29]
It would be useful to be able to notify clients that new SOS offerings are available.

This could be done using the existing notification metadata defined in OGC Service Common but perhaps using a websocket transport instead of WS-Notification.

It could also be done using SWE MQTT channels or using the SensorThings service with MQTT.

**Comment by alexrobin** [comment]
We won't implement this. You can use the SensorWeb API instead to get this functionality.
