### ISSUE TITLE
Admin UI - no more room to add sensor

### ISSUE THREAD

**Issue by mikebotts** [opensensorhub/osh-core#34]
When a hub supports more than about 13-14 sensors, one can no longer scroll down far enough down in the "sensors" tab to click in an open space and pop up the "add sensor" menu items.

NOTE: the field node provides an example of this.

**Comment by alexrobin** [comment]
Just buy a bigger screen... Just kidding ;-)
We can either make sure there is always extra space after the last item, or we can make sure the "Add Module" option is always included in the context menu, even if the click was on an existing item.
