### ISSUE TITLE
Invalid KVP request. Please check your syntax

### ISSUE THREAD

**Issue by josephwinston** [opensensorhub/osh-core#41]
I installed ```osh-v1.1.0-core-install.zip``` and then launched the program.  The following URLs work:

* <http://localhost:8181/sensorhub/test>
* <http://localhost:8181/sensorhub/admin>
* <http://localhost:8181/sensorhub/sos?service=SOS&version=2.0&request=GetCapabilities>
* <http://localhost:8181/sensorhub/sos?service=SOS&version=2.0&request=GetResultTemplate&offering=urn:mysos:offering03&observedProperty=http://sensorml.com/ont/swe/property/Weather>
* <http://localhost:8181/sensorhub/sos?service=SOS&version=2.0&request=GetResult&offering=urn:mysos:offering03&observedProperty=http://sensorml.com/ont/swe/property/Weather&temporalFilter=phenomenonTime,now>
* <http://localhost:8181/sensorhub/sos?service=SOS&version=2.0&request=GetResult&offering=urn:mysos:offering03&observedProperty=http://sensorml.com/ont/swe/property/Weather&temporalFilter=phenomenonTime,2015-01-01/now>

But when I attempt to contact <http://localhost:8181/sensorhub/sos>, I receive:

```
HTTP ERROR: 400

Problem accessing /sensorhub/sos. Reason:

    Invalid KVP request. Please check your syntax
```

Am I doing something wrong (OS Windows 7, Java 1.8.0_102)?

**Comment by alexrobin** [comment]
Hello Joseph,

Everything looks normal. A request directly to the root of the SOS server is invalid. A valid KVP request (i.e. with arguments after the '?') has to be sent to it.

FYI, this HTTP endpoint implements [Sensor Observation Service](http://www.opengeospatial.org/standards/sos) standard interface published by the OGC (Open Geospatial Consortium). We wrote some documentation about it [here](http://docs.opensensorhub.org/user/sos/intro/).

Thanks for your feedback

**Comment by mikebotts** [comment]
Thanks.

---
Dr. Mike Botts
Botts Innovative Research, Inc.
http://www.botts-inc.com
mike.botts@botts-inc.com
256-652-0165

**Comment by josephwinston** [comment]
Thank you for helping me with the issue.  

My confusion was the line ```You can connect to the SOS deployed at http://localhost:8181/sensorhub/sos right away, to get sensor data and metadata:``` from <http://docs.opensensorhub.org/install/>.

On second reading, this part of the sentence refers to the endpoints from the following list.  Maybe changing the introduction to ```You can connect right way to the SOS endpoints.  Here are some examples that work with the installed "fake" sensors.``` would help clarify the text.

**Comment by alexrobin** [comment]
Ok, I see. Thanks for the suggestion. I updated the text of the install section.
