### ISSUE TITLE
Change Default Server Behavior to Enable Transactional?

### ISSUE THREAD

**Issue by mikebotts** [opensensorhub/osh-core#45]
Most OSH servers will probably want to enable transactional capabilities, particularly if Cloud-based. The need to check the configuration UI to enable transactional seems to be a common "I forgot" or "I didn't realize that" during installations. 

Perhaps it would be best to have this enabled by default, perhaps with a hover note to say "uncheck if you don't want sensors to be able to be added through transactional services" or something. I realize that this is a possible security issue for some server, particularly if they don't set fine-grained authentication for transactional, so I'm open to other ideas.

**Comment by alexrobin** [comment]
I suggest we enable it by default, but only in the base distribution to be used with the Android app. What do you think? We also obviously need to improve the documentation.
