### ISSUE TITLE
Build failure: Execution failed for task ':swe-common-core:javadoc' under Unix

### ISSUE THREAD

**Issue by ch08532** [opensensorhub/osh-core#47]
ENVIRONMENT: 

Buidling osh-core from a docker container (Ubuntu 14.04 LTS with Gradle 3.2.1 with Oracle JDK 8 latest)

STEPS:
The gradle build task fails on the following javasdoc task in swe-common-core:

--
/opt/osh/repos/osh-core/lib-swe-common/swe-common-core/src/main/java/org/vast/unit/Unit.java:252: error: unmappable character for encoding ASCII
                                printSymbol = "???C";
                                               ^
/opt/osh/repos/osh-core/lib-swe-common/swe-common-core/src/main/java/org/vast/unit/Unit.java:252: error: unmappable character for encoding ASCII
                                printSymbol = "???C";
                                                ^
/opt/osh/repos/osh-core/lib-swe-common/swe-common-core/src/main/java/org/vast/unit/Unit.java:252: error: unmappable character for encoding ASCII
                                printSymbol = "???C";
                                                 ^
3 errors
:swe-common-core:javadoc FAILED

FAILURE: Build failed with an exception.
--

RESOLUTION: 

add JAVA_TOOL_OPTIONS=-Dfile.encoding=UTF-8 to your environment.

ex: 
export JAVA_TOOL_OPTIONS=-Dfile.encoding=UTF-8
gradle build

**Comment by alexrobin** [comment]
I'm now setting the javadoc encoding option in the main gradle script. Can you let me know if that helps?

**Comment by alexrobin** [comment]
Ok, I confirmed that the fix works when forcing the default system encoding to ASCII, so it should work for you as well

**Comment by ch08532** [comment]
Tested and works! Thanks!
