### ISSUE TITLE
Add capability of retrieving command data via SOS

### ISSUE THREAD

**Issue by sensiasoft** [opensensorhub/osh-core#5]
<a href="https://github.com/sensiasoft"><img src="https://avatars.githubusercontent.com/u/9446498?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [sensiasoft](https://github.com/sensiasoft)**
_Saturday Jan 10, 2015 at 17:36 GMT_
_Originally opened as https://github.com/sensiasoft/sensorhub-core/issues/5_

---

It could be useful to be able to receive high rate command data (either live or historical) viathe SOS interface in order to benefit from the compact swe common encoding. This could be done by implementing 2 new specific SOS data providers.
1. One that listens to command events and forwards the command data to any connected client
2. One that connects to the task storage and fetches historical command data on-demand

**Comment by alexrobin** [comment]
We won't implement this. Use SensorWeb API instead
