### ISSUE TITLE
Add New Sensors Issue

### ISSUE THREAD

**Issue by CLEAOSBORNE** [opensensorhub/osh-core#50]
When I add the sensor jar files to the core lib directory, the  new sensors will not populate or are able to be selected via the OpenSensorHub admin page.  Only the two sensors are included out of the box.....do you have to edit the config.json file to incorporate the new sensors or is there a work around?

**Comment by alexrobin** [comment]
No, there is no configuration needed. This should work but you need to restart OSH after you drop the jars.

**Comment by alexrobin** [comment]
Were you able to make this work?

**Comment by CLEAOSBORNE** [comment]
Yes, thanks....I got it.  I did have an issue with building one specific distro though.  The osh-all distro failed to build and threw the error: Could not read script '/opt/osh-core/include-projects.gradle' as it does not exist.  This is the only distro that wouldn't build out.  Any ideas?  All the required osh-* dependencies are located in the same directory.

**Comment by alexrobin** [comment]
Ok, I'm closing this issue then.
Regarding the osh-all distro, I haven't updated it after the latest changes on the build scripts so things won't build properly at this point...
