### ISSUE TITLE
Add DoS protections

### ISSUE THREAD

**Issue by sensiasoft** [opensensorhub/osh-core#8]
<a href="https://github.com/sensiasoft"><img src="https://avatars.githubusercontent.com/u/9446498?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [sensiasoft](https://github.com/sensiasoft)**
_Saturday Feb 14, 2015 at 17:43 GMT_
_Originally opened as https://github.com/sensiasoft/sensorhub-core/issues/15_

---

It is currently very easy to overload the server by sending many data streams to it. Maybe some low level protections should be activated even when no security front end is used.

**Comment by sensiasoft** [comment]
<a href="https://github.com/sensiasoft"><img src="https://avatars.githubusercontent.com/u/9446498?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [sensiasoft](https://github.com/sensiasoft)**
_Saturday Feb 14, 2015 at 19:05 GMT_

----

First thing to do is enable options for activating Jetty DoS and QoS filters

**Comment by alexrobin** [comment]
Added possibility to override default config with an external Jetty XML config file, which allows to setup the DOs filters.
